Project mefeto {
  database_type: 'PostgreSQL'
}

Table articles as A {
  id int [pk, increment]
  title varchar [not null]
  thumbnail_url varchar [not null]
  short_description text [not null]
  categories varchar[] [not null]
  content text [not null, note: 'HTML content']
  boundary int [default: 35]
  author_id varchar [not null]

  created_at timestamp [not null, default: `now()`]
}

Table article_upvotes {
  article_id int [pk, not null, ref: > A.id]
  user_id varchar [pk, not null]
  created_at timestamp [not null, default: `now()`]
}
