Project mefeto {
  database_type: 'PostgreSQL'
}

Table articles {
  id int [pk, increment]
  title varchar [not null]
  thumbnail_url varchar [not null]
  short_description text [not null]
  categories varchar[] [not null]
  content text [not null, note: 'HTML content']
  boundary int [default: 35]

  created_at timestamp [not null, default: `now()`]
}
