export const parliamentList: Array<{
  HG_NM: string;
  T_URL: string | null;
  F_URL: string | null;
  Y_URL: string | null;
  B_URL: string | null;
  MONA_CD: string;
}> = [
  {
    HG_NM: "강기윤",
    T_URL: null,
    F_URL: "https://web.facebook.com/ggotop",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "14M56632",
  },
  {
    HG_NM: "강대식",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/kds21341",
    MONA_CD: "L2I9861C",
  },
  {
    HG_NM: "강득구",
    T_URL: null,
    F_URL: "https://web.facebook.com/dulipapa2",
    Y_URL: "https://www.youtube.com/channel/channel/UCWPYeOndgzUJ2atd1NwpBTw",
    B_URL: "https://blog.naver.com/dulipapa",
    MONA_CD: "8P37634C",
  },
  {
    HG_NM: "강민국",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "GX22581L",
  },
  {
    HG_NM: "강민정",
    T_URL: null,
    F_URL: "https://web.facebook.com/100005179623842",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "P2N50879",
  },
  {
    HG_NM: "강병원",
    T_URL: null,
    F_URL: "https://web.facebook.com/kbw89",
    Y_URL: "https://www.youtube.com/c/강병원tv",
    B_URL: "https://blog.naver.com/kangbw89",
    MONA_CD: "60490713",
  },
  {
    HG_NM: "강선우",
    T_URL: "https://twitter.com/gangseonsunwoo",
    F_URL: "https://web.facebook.com/kangsunwooo",
    Y_URL: "https://www.youtube.com/channel/UCTDli6TqWf2P-mWuJpFby3w",
    B_URL: null,
    MONA_CD: "MNZ4401T",
  },
  {
    HG_NM: "강성희",
    T_URL: "https://twitter.com/kangjinbo",
    F_URL: "https://web.facebook.com/kangjinbo",
    Y_URL: "https://www.youtube.com/kangjinbo",
    B_URL: "https://blog.naver.com/kangjinbo",
    MONA_CD: "6FS10566",
  },
  {
    HG_NM: "강은미",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/em7086",
    MONA_CD: "WMG57662",
  },
  {
    HG_NM: "강준현",
    T_URL: null,
    F_URL: "https://web.facebook.com/junhyeon.gang",
    Y_URL: null,
    B_URL: "https://blog.naver.com/withusone2020",
    MONA_CD: "5KV96424",
  },
  {
    HG_NM: "강훈식",
    T_URL: null,
    F_URL: "https://web.facebook.com/gohoonsik",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "TRE2429O",
  },
  {
    HG_NM: "고민정",
    T_URL: null,
    F_URL: "https://web.facebook.com/minjung.ko.184",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "WCD5518S",
  },
  {
    HG_NM: "고영인",
    T_URL: null,
    F_URL: "https://web.facebook.com/koyoungin4853",
    Y_URL: "https://www.youtube.com/channel/UCaaIRghu-ZjqIdKe0-ZbShA",
    B_URL: "https://blog.naver.com/kyi4853",
    MONA_CD: "4XG1439M",
  },
  {
    HG_NM: "고용진",
    T_URL: "https://twitter.com/yongjin_koh",
    F_URL: "https://web.facebook.com/yongjin.koh",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "6V37131U",
  },
  {
    HG_NM: "구자근",
    T_URL: null,
    F_URL: "https://web.facebook.com/can929292",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "7469929V",
  },
  {
    HG_NM: "권명호",
    T_URL: null,
    F_URL: "https://web.facebook.com/kmh365",
    Y_URL: null,
    B_URL: "https://blog.naver.com/kmh330575",
    MONA_CD: "E9R4507P",
  },
  {
    HG_NM: "권성동",
    T_URL: "https://twitter.com/ksdd22",
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "GDG1847Z",
  },
  {
    HG_NM: "권영세",
    T_URL: "https://twitter.com/yskys2020",
    F_URL: "https://web.facebook.com/yskys2020",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "LG63087O",
  },
  {
    HG_NM: "권은희",
    T_URL: null,
    F_URL: "https://web.facebook.com/kwoneh0215",
    Y_URL: "https://www.youtube.com/c/권은희TV",
    B_URL: "https://blog.naver.com/kehsuda",
    MONA_CD: "YKW37422",
  },
  {
    HG_NM: "권인숙",
    T_URL: null,
    F_URL: "https://web.facebook.com/insook.kwon.31",
    Y_URL: null,
    B_URL: "https://blog.naver.com/iskwon317",
    MONA_CD: "3TO11703",
  },
  {
    HG_NM: "권칠승",
    T_URL: "https://twitter.com/k7win_",
    F_URL: "https://web.facebook.com/k7win",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "C7E79345",
  },
  {
    HG_NM: "기동민",
    T_URL: null,
    F_URL: "https://web.facebook.com/dongmin.gi",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "B7R2742J",
  },
  {
    HG_NM: "김경만",
    T_URL: null,
    F_URL: "https://web.facebook.com/2020kkman",
    Y_URL:
      "https://www.youtube.com/channel/channel/UCe8nULGCZrf0u8OfX6FQt3w?view_as=subscriber",
    B_URL: "https://blog.naver.com/2020kkman",
    MONA_CD: "1BX7234U",
  },
  {
    HG_NM: "김경협",
    T_URL: "https://twitter.com/kimghkr",
    F_URL: "https://web.facebook.com/kimgyunghyub",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ZKU88693",
  },
  {
    HG_NM: "김교흥",
    T_URL: null,
    F_URL: "https://web.facebook.com/kimkyoheung",
    Y_URL: "https://www.youtube.com/channel/UCjtmX6KDX7bGP6U1MW2KeCQ",
    B_URL: "https://blog.naver.com/kimkh4u",
    MONA_CD: "X1K3667J",
  },
  {
    HG_NM: "김기현",
    T_URL: null,
    F_URL: "https://web.facebook.com/eutface",
    Y_URL:
      "https://www.youtube.com/channel/UCHBN4fWr8xsqjg7MVKx8mDg?view_as=subscriber",
    B_URL: "https://blog.naver.com/eutsarang",
    MONA_CD: "X7I4680R",
  },
  {
    HG_NM: "김남국",
    T_URL: "https://twitter.com/lawmaker2024",
    F_URL: "https://web.facebook.com/lawmaker2020",
    Y_URL: "https://www.youtube.com/channel/channel/UC5ylgZz6hi0eCIzAq7y5H9g",
    B_URL: "https://blog.naver.com/lawmaker12",
    MONA_CD: "QHL3248U",
  },
  {
    HG_NM: "김도읍",
    T_URL: "https://twitter.com/ldek3525",
    F_URL: "https://web.facebook.com/ldek3525",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "LH97552Q",
  },
  {
    HG_NM: "김두관",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CI15627C",
  },
  {
    HG_NM: "김미애",
    T_URL: null,
    F_URL: "https://web.facebook.com/lawyerkimmiae",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "3BC6890E",
  },
  {
    HG_NM: "김민기",
    T_URL: null,
    F_URL: "https://web.facebook.com/kminki84",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "NTT8182Q",
  },
  {
    HG_NM: "김민석",
    T_URL: null,
    F_URL: "https://web.facebook.com/minseok.kim.376043",
    Y_URL: "https://www.youtube.com/channel/channel/UC0xm3nsJXdMEA6ILZRHCXvQ",
    B_URL: "https://blog.naver.com/newmskim2030",
    MONA_CD: "MLH1404S",
  },
  {
    HG_NM: "김민철",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/kmc8952",
    MONA_CD: "6399076T",
  },
  {
    HG_NM: "김병기",
    T_URL: null,
    F_URL: "https://web.facebook.com/the.kim.weapon",
    Y_URL: null,
    B_URL: "https://blog.naver.com/kim-weapon",
    MONA_CD: "8Q88373R",
  },
  {
    HG_NM: "김병욱",
    T_URL: null,
    F_URL: "https://web.facebook.com/byongwook.kim",
    Y_URL: null,
    B_URL: "https://blog.naver.com/ilungkim",
    MONA_CD: "KB04377U",
  },
  {
    HG_NM: "김병욱",
    T_URL: null,
    F_URL: "https://web.facebook.com/777byung",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "GFF1986K",
  },
  {
    HG_NM: "김병주",
    T_URL: null,
    F_URL: "https://web.facebook.com/byungjoobyungjoo",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "GF286398",
  },
  {
    HG_NM: "김상훈",
    T_URL: null,
    F_URL: "https://web.facebook.com/kshdg11",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "1Y73132H",
  },
  {
    HG_NM: "김상희",
    T_URL: null,
    F_URL: "https://web.facebook.com/sosakim407",
    Y_URL: "https://www.youtube.com/channel/channel/UCXrYmWVl5BB17D69nLmSxCQ",
    B_URL: "https://blog.naver.com/shk407",
    MONA_CD: "UGH6481E",
  },
  {
    HG_NM: "김석기",
    T_URL: null,
    F_URL: "https://web.facebook.com/podoripapa",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ZYP7962W",
  },
  {
    HG_NM: "김성원",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "9D939735",
  },
  {
    HG_NM: "김성주",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "2UD1340H",
  },
  {
    HG_NM: "김성환",
    T_URL: "https://twitter.com/no1nowon",
    F_URL: "https://web.facebook.com/no1nowon",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "XSP20229",
  },
  {
    HG_NM: "김수흥",
    T_URL: null,
    F_URL: "https://web.facebook.com/7979iksan",
    Y_URL: null,
    B_URL: "https://blog.naver.com/iksan832",
    MONA_CD: "L7T64271",
  },
  {
    HG_NM: "김승남",
    T_URL: null,
    F_URL: "https://web.facebook.com/snk1006",
    Y_URL: null,
    B_URL: "https://blog.naver.com/snk0411",
    MONA_CD: "P2N4585G",
  },
  {
    HG_NM: "김승수",
    T_URL: null,
    F_URL: "https://web.facebook.com/kiminnotank2",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "5K93695T",
  },
  {
    HG_NM: "김승원",
    T_URL: "https://twitter.com/sw_with_suwon",
    F_URL: "https://web.facebook.com/telgasem",
    Y_URL: "https://www.youtube.com/c/김승원TV",
    B_URL: "https://blog.naver.com/sw_with_suwon",
    MONA_CD: "ATB59635",
  },
  {
    HG_NM: "김영배",
    T_URL: null,
    F_URL: "https://web.facebook.com/clubyb0415",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "B7D7534L",
  },
  {
    HG_NM: "김영선",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "LBC8144B",
  },
  {
    HG_NM: "김영식",
    T_URL: null,
    F_URL: "https://web.facebook.com/https://m.facebook.com/gumiyeungshik",
    Y_URL: null,
    B_URL: "https://blog.naver.com/yeungshik20",
    MONA_CD: "IOW1101J",
  },
  {
    HG_NM: "김영주",
    T_URL: null,
    F_URL: "https://web.facebook.com/youngjoo2012",
    Y_URL: "https://www.youtube.com/channel/UCQTj2pHvchQoLQXjHKuw8mg",
    B_URL: null,
    MONA_CD: "0W194007",
  },
  {
    HG_NM: "김영진",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "5765663F",
  },
  {
    HG_NM: "김영호",
    T_URL: "https://twitter.com/minjoo05",
    F_URL: "https://web.facebook.com/stookim",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "7BM2933Y",
  },
  {
    HG_NM: "김예지",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CNZ51556",
  },
  {
    HG_NM: "김용민",
    T_URL: null,
    F_URL: "https://web.facebook.com/fopeople",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "OFE45081",
  },
  {
    HG_NM: "김용판",
    T_URL: null,
    F_URL: "https://web.facebook.com/kyp8969",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "SVH3899R",
  },
  {
    HG_NM: "김웅",
    T_URL: null,
    F_URL: "https://web.facebook.com/songpawoong",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "LQW3652K",
  },
  {
    HG_NM: "김원이",
    T_URL: null,
    F_URL: "https://web.facebook.com/kimwoni8182",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "4L695580",
  },
  {
    HG_NM: "김윤덕",
    T_URL: null,
    F_URL: "https://web.facebook.com/ydkim22",
    Y_URL: null,
    B_URL: "https://blog.naver.com/ydkim22",
    MONA_CD: "JZY9937U",
  },
  {
    HG_NM: "김의겸",
    T_URL: "https://twitter.com/kyummy63",
    F_URL: "https://web.facebook.com/kyummy63",
    Y_URL: "https://www.youtube.com/channel/UCLwDpdPbcsq0R2398JO_oWQ",
    B_URL: "https://blog.naver.com/kek9580",
    MONA_CD: "FIC9046Z",
  },
  {
    HG_NM: "김정재",
    T_URL: null,
    F_URL: "https://web.facebook.com/lawjj909",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "E1J8836Y",
  },
  {
    HG_NM: "김정호",
    T_URL: "https://twitter.com/kimjungho3359",
    F_URL: "https://web.facebook.com/kimjungho3359",
    Y_URL: "https://www.youtube.com/channel/UCXEu8xyS1u7POLvhhxq0fTA",
    B_URL: "https://blog.naver.com/bongha4rang",
    MONA_CD: "9LD2641Q",
  },
  {
    HG_NM: "김종민",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "M2Q9024I",
  },
  {
    HG_NM: "김주영",
    T_URL: "https://twitter.com/GimpoLOVE_kjy",
    F_URL: "https://web.facebook.com/kimjuyoung60",
    Y_URL: "https://www.youtube.com/c/김주영TV",
    B_URL: "https://blog.naver.com/peoplewin60",
    MONA_CD: "D6U6678O",
  },
  {
    HG_NM: "김진표",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "Q9H5708M",
  },
  {
    HG_NM: "김철민",
    T_URL: "https://twitter.com/kimcm8764",
    F_URL: "https://web.facebook.com/kcm8764",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "1MU99298",
  },
  {
    HG_NM: "김태년",
    T_URL: "https://twitter.com/kimtaenyeon",
    F_URL: "https://web.facebook.com/kimtaenyeon",
    Y_URL: "https://www.youtube.com/c/김태년TV",
    B_URL: null,
    MONA_CD: "1WE5693J",
  },
  {
    HG_NM: "김태호",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "P0F1530P",
  },
  {
    HG_NM: "김학용",
    T_URL: null,
    F_URL: "https://web.facebook.com/kimhackyong",
    Y_URL: "https://www.youtube.com/c/안성맞춤김학용",
    B_URL: null,
    MONA_CD: "F5U2979W",
  },
  {
    HG_NM: "김한규",
    T_URL: null,
    F_URL: "https://web.facebook.com/http://www.facebook.com/hanqkim74",
    Y_URL: "https://www.youtube.com/c/hanqkim74",
    B_URL: "https://blog.naver.com/https://blog.naver.com/hanqkim74",
    MONA_CD: "NUB4941Z",
  },
  {
    HG_NM: "김한정",
    T_URL: "https://twitter.com/hanjungok",
    F_URL: "https://web.facebook.com/hanjungkim21",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "09I2323E",
  },
  {
    HG_NM: "김형동",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/khyungdong",
    MONA_CD: "JEZ3130Q",
  },
  {
    HG_NM: "김홍걸",
    T_URL: "https://twitter.com/hgk615",
    F_URL: "https://web.facebook.com/hgk615",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "PO64874I",
  },
  {
    HG_NM: "김회재",
    T_URL: null,
    F_URL: "https://web.facebook.com/hoijae.kim.35",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "M6H1705E",
  },
  {
    HG_NM: "김희곤",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "52P3934K",
  },
  {
    HG_NM: "김희국",
    T_URL: null,
    F_URL: "https://web.facebook.com/unclekim1020",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "6AR6743G",
  },
  {
    HG_NM: "남인순",
    T_URL: "https://twitter.com/nisoon",
    F_URL: "https://web.facebook.com/nisoon",
    Y_URL: "https://www.youtube.com/user/flynisoon",
    B_URL: "https://blog.naver.com/nisoon",
    MONA_CD: "04T3751T",
  },
  {
    HG_NM: "노용호",
    T_URL: null,
    F_URL: "https://web.facebook.com/ryh4711",
    Y_URL: null,
    B_URL: "https://blog.naver.com/ryh4711",
    MONA_CD: "JVB6983V",
  },
  {
    HG_NM: "노웅래",
    T_URL: null,
    F_URL: "https://web.facebook.com/wraenoh",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "0827740Q",
  },
  {
    HG_NM: "도종환",
    T_URL: null,
    F_URL: "https://web.facebook.com/djhpoem",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "J2O8643H",
  },
  {
    HG_NM: "류성걸",
    T_URL: null,
    F_URL: "https://web.facebook.com/sungkull",
    Y_URL: "https://www.youtube.com/channel/UCvUzEYjZSyTrlVf-NIRoK3w",
    B_URL: "https://blog.naver.com/sungkull",
    MONA_CD: "8VY63414",
  },
  {
    HG_NM: "류호정",
    T_URL: "https://twitter.com/@ryuhojeong_twit",
    F_URL: "https://web.facebook.com/ryuhojeong.official",
    Y_URL: "https://www.youtube.com/c/ryutube",
    B_URL: "https://blog.naver.com/ryuhojeong.com",
    MONA_CD: "NCP9875N",
  },
  {
    HG_NM: "맹성규",
    T_URL: null,
    F_URL: "https://web.facebook.com/namdong.maeng",
    Y_URL: null,
    B_URL: "https://blog.naver.com/minjoo_maeng",
    MONA_CD: "FJK3396E",
  },
  {
    HG_NM: "문정복",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "GOC54665",
  },
  {
    HG_NM: "문진석",
    T_URL: null,
    F_URL: "https://web.facebook.com/profile.php?id=100024518042012&amp;_rdr",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "4U29186R",
  },
  {
    HG_NM: "민병덕",
    T_URL: "https://twitter.com/anyangmin",
    F_URL: "https://web.facebook.com/anyangmin",
    Y_URL: "https://www.youtube.com/user/MrAnyangmin",
    B_URL: "https://blog.naver.com/anyangmin",
    MONA_CD: "TZ228122",
  },
  {
    HG_NM: "민형배",
    T_URL: null,
    F_URL: "https://web.facebook.com/minhyungbae1",
    Y_URL: "https://www.youtube.com/channel/channel/UC1M1iWQhaGvAoVuKDEPrJTQ",
    B_URL: "https://blog.naver.com/gjminsim",
    MONA_CD: "VRY5522V",
  },
  {
    HG_NM: "민홍철",
    T_URL: "https://twitter.com/minstar21c",
    F_URL: "https://web.facebook.com/hongchul.min.1",
    Y_URL: null,
    B_URL: "https://blog.naver.com/rediron2400",
    MONA_CD: "O6D8329R",
  },
  {
    HG_NM: "박광온",
    T_URL: "https://twitter.com/parkkwangon",
    F_URL: "https://web.facebook.com/parkkwangon",
    Y_URL: "https://www.youtube.com/c/박광온TV",
    B_URL: null,
    MONA_CD: "K3W33496",
  },
  {
    HG_NM: "박대수",
    T_URL: null,
    F_URL: "https://web.facebook.com/pds0830",
    Y_URL: null,
    B_URL: "https://blog.naver.com/pds0830",
    MONA_CD: "B7H6207C",
  },
  {
    HG_NM: "박대출",
    T_URL: "https://twitter.com/dcparkjj",
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "W4X85128",
  },
  {
    HG_NM: "박덕흠",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "N4R2421C",
  },
  {
    HG_NM: "박범계",
    T_URL: "https://twitter.com/bkfire1004",
    F_URL: "https://web.facebook.com/bkfire",
    Y_URL: "https://www.youtube.com/user/bkfire1004",
    B_URL: "https://blog.naver.com/bkfire1004",
    MONA_CD: "7R156073",
  },
  {
    HG_NM: "박병석",
    T_URL: "https://twitter.com/pbs2100",
    F_URL: "https://web.facebook.com/pbs21",
    Y_URL: "https://www.youtube.com/user/pbs2100",
    B_URL: "https://blog.naver.com/pbs2100",
    MONA_CD: "BLC8630L",
  },
  {
    HG_NM: "박상혁",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "HXT76735",
  },
  {
    HG_NM: "박성민",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "X3170462",
  },
  {
    HG_NM: "박성준",
    T_URL: null,
    F_URL: "https://web.facebook.com/sungjoon.park.37669",
    Y_URL: null,
    B_URL: "https://blog.naver.com/pksjoffice",
    MONA_CD: "IL74008M",
  },
  {
    HG_NM: "박성중",
    T_URL: "https://twitter.com/parksungjoong",
    F_URL: "https://web.facebook.com/sjpark101",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "DAN6731C",
  },
  {
    HG_NM: "박수영",
    T_URL: null,
    F_URL: "https://web.facebook.com/sooyoung.park.165",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "FU87526G",
  },
  {
    HG_NM: "박영순",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "40S1959J",
  },
  {
    HG_NM: "박완주",
    T_URL: "https://twitter.com/park_wanju",
    F_URL: "https://web.facebook.com/parkwanju",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "A3H7195R",
  },
  {
    HG_NM: "박용진",
    T_URL: "https://twitter.com/hopeparkyongjin",
    F_URL: "https://web.facebook.com/yongjin.bag",
    Y_URL: "https://www.youtube.com/hopeparkyongjin",
    B_URL: null,
    MONA_CD: "PEP6922S",
  },
  {
    HG_NM: "박재호",
    T_URL: "https://twitter.com/ourpark",
    F_URL: "https://web.facebook.com/ourpark20",
    Y_URL: "https://www.youtube.com/c/박재호TV",
    B_URL: "https://blog.naver.com/pjh0586",
    MONA_CD: "QUO78839",
  },
  {
    HG_NM: "박정",
    T_URL: "https://twitter.com/pjkorea21c",
    F_URL: "https://web.facebook.com/pjkorea21c",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "4019850M",
  },
  {
    HG_NM: "박정하",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/newwonju2016",
    MONA_CD: "6RD62559",
  },
  {
    HG_NM: "박주민",
    T_URL: "https://twitter.com/yoeman6310",
    F_URL: "https://web.facebook.com/joomin.park.739",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "6AU2417B",
  },
  {
    HG_NM: "박진",
    T_URL: null,
    F_URL: "https://web.facebook.com/parkjin.official",
    Y_URL: "https://www.youtube.com/channel/UCiYvx52uqRBMxn5NBAh-BYQ",
    B_URL: "https://blog.naver.com/parkjin916",
    MONA_CD: "QKO6165V",
  },
  {
    HG_NM: "박찬대",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "BT62420K",
  },
  {
    HG_NM: "박형수",
    T_URL: null,
    F_URL: "https://web.facebook.com/hyeungsoo",
    Y_URL: null,
    B_URL: "https://blog.naver.com/hyeungsoo1",
    MONA_CD: "6U243644",
  },
  {
    HG_NM: "박홍근",
    T_URL: null,
    F_URL: "https://web.facebook.com/maumgil",
    Y_URL: null,
    B_URL: "https://blog.naver.com/bakhonggeun",
    MONA_CD: "S824682L",
  },
  {
    HG_NM: "배준영",
    T_URL: null,
    F_URL: "https://web.facebook.com/jyb116",
    Y_URL: "https://www.youtube.com/channel/UCxKQm25dzAAA_XYWQ4S_uZw",
    B_URL: "https://blog.naver.com/m.jyb116",
    MONA_CD: "QQP4727N",
  },
  {
    HG_NM: "배진교",
    T_URL: null,
    F_URL: "https://web.facebook.com/baejingyo",
    Y_URL: null,
    B_URL: "https://blog.naver.com/bjg21",
    MONA_CD: "A2V51235",
  },
  {
    HG_NM: "배현진",
    T_URL: null,
    F_URL: "https://web.facebook.com/trustbae83",
    Y_URL: "https://www.youtube.com/배현진",
    B_URL: "https://blog.naver.com/trustbhj",
    MONA_CD: "4X525582",
  },
  {
    HG_NM: "백종헌",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CAA7713A",
  },
  {
    HG_NM: "백혜련",
    T_URL: "https://twitter.com/100hyeryun",
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "HSS7466Y",
  },
  {
    HG_NM: "변재일",
    T_URL: null,
    F_URL: "https://web.facebook.com/open1197",
    Y_URL: null,
    B_URL: "https://blog.naver.com/open1197news",
    MONA_CD: "MO52543L",
  },
  {
    HG_NM: "서동용",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/dyongseo",
    MONA_CD: "0PK7354M",
  },
  {
    HG_NM: "서범수",
    T_URL: null,
    F_URL: "https://web.facebook.com/suhbumsoo",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "L7J93733",
  },
  {
    HG_NM: "서병수",
    T_URL: null,
    F_URL: "https://web.facebook.com/suhbyungsoo",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CT85313K",
  },
  {
    HG_NM: "서삼석",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/3s0011",
    MONA_CD: "FOK3459D",
  },
  {
    HG_NM: "서영교",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "TKJ4800F",
  },
  {
    HG_NM: "서영석",
    T_URL: "https://twitter.com/unclevitamn",
    F_URL: "https://web.facebook.com/ojungvitamin",
    Y_URL: null,
    B_URL: "https://blog.naver.com/guseng",
    MONA_CD: "XR24352K",
  },
  {
    HG_NM: "서일준",
    T_URL: null,
    F_URL: "https://web.facebook.com/greatgeoje",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "MR210505",
  },
  {
    HG_NM: "서정숙",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "WFU14784",
  },
  {
    HG_NM: "설훈",
    T_URL: "https://twitter.com/sulhoon",
    F_URL: "https://web.facebook.com/sulhoon",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "OW53107J",
  },
  {
    HG_NM: "성일종",
    T_URL: null,
    F_URL: "https://web.facebook.com/sij5140",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "7XY7109I",
  },
  {
    HG_NM: "소병철",
    T_URL: null,
    F_URL: "https://web.facebook.com/sobyungchul20",
    Y_URL: "https://www.youtube.com/channel/UCMEw9KjrmjmlqLYeWyINcjg",
    B_URL: null,
    MONA_CD: "17M85910",
  },
  {
    HG_NM: "소병훈",
    T_URL: "https://twitter.com/sotongsa",
    F_URL: "https://web.facebook.com/sotongsa1",
    Y_URL: null,
    B_URL: "https://blog.naver.com/sotongsa",
    MONA_CD: "ZDR63255",
  },
  {
    HG_NM: "송갑석",
    T_URL: null,
    F_URL: "https://web.facebook.com/songkapseok",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "RD42006Y",
  },
  {
    HG_NM: "송기헌",
    T_URL: null,
    F_URL: "https://web.facebook.com/withsong",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "SQ36001H",
  },
  {
    HG_NM: "송석준",
    T_URL: null,
    F_URL: "https://web.facebook.com/icheonsarang",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CNW5754J",
  },
  {
    HG_NM: "송언석",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "6EN68926",
  },
  {
    HG_NM: "송옥주",
    T_URL: null,
    F_URL: "https://web.facebook.com/okju.song.52",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "3249208I",
  },
  {
    HG_NM: "송재호",
    T_URL: null,
    F_URL: "https://web.facebook.com/song.jeju2",
    Y_URL: "https://www.youtube.com/channel/UC-I8c113p-KfHnfY7zrj6PA",
    B_URL: "https://blog.naver.com/song-jeju",
    MONA_CD: "LM13674V",
  },
  {
    HG_NM: "신동근",
    T_URL: "https://twitter.com/skdc2875",
    F_URL: "https://web.facebook.com/shindonggen",
    Y_URL: null,
    B_URL: "https://blog.naver.com/skdc2875",
    MONA_CD: "G1570880",
  },
  {
    HG_NM: "신영대",
    T_URL: null,
    F_URL: "https://web.facebook.com/shingunsan",
    Y_URL: "https://www.youtube.com/channel/UCLFn1-WikFrCbHISlGo3Yrg/featured",
    B_URL: "https://blog.naver.com/shinyd85",
    MONA_CD: "AFH96856",
  },
  {
    HG_NM: "신원식",
    T_URL: null,
    F_URL: "https://web.facebook.com/shin.general.58",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "SRP7336N",
  },
  {
    HG_NM: "신정훈",
    T_URL: null,
    F_URL: "https://web.facebook.com/newnaju21",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "M7O7878U",
  },
  {
    HG_NM: "신현영",
    T_URL: "https://twitter.com/shy740",
    F_URL: "https://web.facebook.com/shy740",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "F5Y4026Q",
  },
  {
    HG_NM: "심상정",
    T_URL: "https://twitter.com/sangjungsim",
    F_URL: "https://web.facebook.com/simsangjung",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "SU53086M",
  },
  {
    HG_NM: "안규백",
    T_URL: null,
    F_URL: "https://web.facebook.com/agbhope",
    Y_URL: "https://www.youtube.com/user/intoan429",
    B_URL: "https://blog.naver.com/agbhope",
    MONA_CD: "TST4507I",
  },
  {
    HG_NM: "안민석",
    T_URL: "https://twitter.com/eduhimang",
    F_URL: "https://web.facebook.com/osan21",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ZA54991S",
  },
  {
    HG_NM: "안병길",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "6MO8786S",
  },
  {
    HG_NM: "안철수",
    T_URL: "https://twitter.com/cheolsoo0919",
    F_URL: "https://web.facebook.com/ahncs111",
    Y_URL: "https://www.youtube.com/user/jinsimcamp",
    B_URL: "https://blog.naver.com/ahncs0518",
    MONA_CD: "YOG1280B",
  },
  {
    HG_NM: "안호영",
    T_URL: null,
    F_URL: "https://web.facebook.com/ahnho065",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "XEF29171",
  },
  {
    HG_NM: "양경숙",
    T_URL: null,
    F_URL: "https://web.facebook.com/yanggyeonsug",
    Y_URL: "https://www.youtube.com/channel/UCCDtA3wo0jnnxI2cwXYLNIA",
    B_URL: null,
    MONA_CD: "9V18755A",
  },
  {
    HG_NM: "양금희",
    T_URL: null,
    F_URL: "https://web.facebook.com/ygoldh8999",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "VG24001G",
  },
  {
    HG_NM: "양기대",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "KUO3574J",
  },
  {
    HG_NM: "양이원영",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "7O71647Z",
  },
  {
    HG_NM: "양정숙",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "PZA4062H",
  },
  {
    HG_NM: "양향자",
    T_URL: null,
    F_URL: "https://web.facebook.com/bestwest1967",
    Y_URL: null,
    B_URL: "https://blog.naver.com/bestwest1967",
    MONA_CD: "WHV3448W",
  },
  {
    HG_NM: "어기구",
    T_URL: null,
    F_URL: "https://web.facebook.com/ekkw2012",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "8FB1535Y",
  },
  {
    HG_NM: "엄태영",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "8348421R",
  },
  {
    HG_NM: "오기형",
    T_URL: "https://twitter.com/vic_ohgh(01049961986)",
    F_URL: "https://web.facebook.com/01050900177",
    Y_URL: "https://www.youtube.com/@TV_ug4xg",
    B_URL: "https://blog.naver.com/okgihyoung",
    MONA_CD: "OIA3741M",
  },
  {
    HG_NM: "오영환",
    T_URL: null,
    F_URL: "https://web.facebook.com/ER.O.119",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "MY318392",
  },
  {
    HG_NM: "용혜인",
    T_URL: "https://twitter.com/yong_hyein",
    F_URL: "https://web.facebook.com/YONGHYEIN.BASICINCOME",
    Y_URL: "https://www.youtube.com/channel/UCnkuuG3n7_S53gSzGpulyJA",
    B_URL: "https://blog.naver.com/yong_hyein",
    MONA_CD: "GE71932C",
  },
  {
    HG_NM: "우상호",
    T_URL: null,
    F_URL: "https://web.facebook.com/woosangho",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "V0O5343U",
  },
  {
    HG_NM: "우원식",
    T_URL: "https://twitter.com/wonsikw",
    F_URL: "https://web.facebook.com/wonsikw",
    Y_URL: "https://www.youtube.com/c/wonsikw",
    B_URL: "https://blog.naver.com/reform111",
    MONA_CD: "XBT9550Q",
  },
  {
    HG_NM: "위성곤",
    T_URL: "https://twitter.com/wisg1128",
    F_URL: "https://web.facebook.com/seogwipowsg",
    Y_URL: "https://www.youtube.com/channel/UCAFjsCaWERftqIbP_OjZU7Q",
    B_URL: "https://blog.naver.com/wishjeju",
    MONA_CD: "RQQ3807K",
  },
  {
    HG_NM: "유경준",
    T_URL: null,
    F_URL: "https://web.facebook.com/gangnam4you",
    Y_URL: "https://www.youtube.com/channel/UCLoTfV2nzkVEpz9HwLcsXvw",
    B_URL: "https://blog.naver.com/gangnamforyou",
    MONA_CD: "9L57027L",
  },
  {
    HG_NM: "유기홍",
    T_URL: "https://twitter.com/yookihong",
    F_URL: "https://web.facebook.com/58kihong",
    Y_URL:
      "https://www.youtube.com/c/%EC%9C%A0%EA%B8%B0%ED%99%8D%ED%8A%9C%EB%B8%8C",
    B_URL: "https://blog.naver.com/youngkor",
    MONA_CD: "8FC9697X",
  },
  {
    HG_NM: "유동수",
    T_URL: null,
    F_URL: "https://web.facebook.com/newds2016",
    Y_URL: null,
    B_URL: "https://blog.naver.com/newds61",
    MONA_CD: "GX38539O",
  },
  {
    HG_NM: "유상범",
    T_URL: null,
    F_URL: "https://web.facebook.com/sbyoo64",
    Y_URL: "https://www.youtube.com/c/유상범TV",
    B_URL: "https://blog.naver.com/sbyoo64",
    MONA_CD: "MU69217P",
  },
  {
    HG_NM: "유의동",
    T_URL: null,
    F_URL: "https://web.facebook.com/ptopen730",
    Y_URL: null,
    B_URL: "https://blog.naver.com/ptopen730",
    MONA_CD: "MRK4871S",
  },
  {
    HG_NM: "유정주",
    T_URL: null,
    F_URL: "https://web.facebook.com/sunmoon905",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "0WL9321T",
  },
  {
    HG_NM: "윤건영",
    T_URL: "https://twitter.com/yky2015",
    F_URL: "https://web.facebook.com/yky2015",
    Y_URL: "https://www.youtube.com/c/윤건영TV",
    B_URL: "https://blog.naver.com/yky2015",
    MONA_CD: "GP07421U",
  },
  {
    HG_NM: "윤관석",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "JMY9959W",
  },
  {
    HG_NM: "윤두현",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "7JC3239L",
  },
  {
    HG_NM: "윤미향",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/mhyang530",
    MONA_CD: "KNM3215T",
  },
  {
    HG_NM: "윤상현",
    T_URL: "https://twitter.com/sanghyun_yoon",
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "MSY7784L",
  },
  {
    HG_NM: "윤영덕",
    T_URL: null,
    F_URL: "https://web.facebook.com/yoonyd",
    Y_URL: "https://www.youtube.com/channel/UCeUkYl5Z_aY_CVVogx37NHQ",
    B_URL: "https://blog.naver.com/yyd0415v",
    MONA_CD: "KFS1358P",
  },
  {
    HG_NM: "윤영석",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "9VR65006",
  },
  {
    HG_NM: "윤영찬",
    T_URL: "https://twitter.com/yyc1964",
    F_URL: "https://web.facebook.com/youngchan.yoon.18",
    Y_URL: "https://www.youtube.com/@YoungchanTV",
    B_URL: "https://blog.naver.com/yyc8361",
    MONA_CD: "XWX1513T",
  },
  {
    HG_NM: "윤재갑",
    T_URL: null,
    F_URL: "https://web.facebook.com/groups/619252435315496",
    Y_URL: null,
    B_URL: "https://blog.naver.com/jaekab542",
    MONA_CD: "SE233396",
  },
  {
    HG_NM: "윤재옥",
    T_URL: "https://twitter.com/yunjaeok",
    F_URL: "https://web.facebook.com/yunjaeok",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ZRF3039U",
  },
  {
    HG_NM: "윤주경",
    T_URL: null,
    F_URL: "https://web.facebook.com/jkyoon828",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ZDP5704Q",
  },
  {
    HG_NM: "윤준병",
    T_URL: "https://twitter.com/theminjb",
    F_URL: "https://web.facebook.com/joonbyeong.yoon",
    Y_URL: "https://www.youtube.com/https://www.youtube.com/@yjb_theminjoo",
    B_URL: null,
    MONA_CD: "JC14718Q",
  },
  {
    HG_NM: "윤창현",
    T_URL: null,
    F_URL: "https://web.facebook.com/yunch5270",
    Y_URL: "https://www.youtube.com/@yunchanghyuntube",
    B_URL: "https://blog.naver.com/yunch5270",
    MONA_CD: "40E3739H",
  },
  {
    HG_NM: "윤한홍",
    T_URL: null,
    F_URL: "https://web.facebook.com/uhh609",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "8X15119P",
  },
  {
    HG_NM: "윤호중",
    T_URL: null,
    F_URL: "https://web.facebook.com/hojung.yun",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "M0A1658U",
  },
  {
    HG_NM: "윤후덕",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "O7R5461J",
  },
  {
    HG_NM: "이개호",
    T_URL: null,
    F_URL: "https://web.facebook.com/leegaeho",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "I7R13867",
  },
  {
    HG_NM: "이달곤",
    T_URL: null,
    F_URL: "https://web.facebook.com/dalgon.lee.77",
    Y_URL: null,
    B_URL: "https://blog.naver.com/ldg200020",
    MONA_CD: "QUM8288K",
  },
  {
    HG_NM: "이동주",
    T_URL: "https://twitter.com/hmright",
    F_URL: "https://web.facebook.com/hmright",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "RO593601",
  },
  {
    HG_NM: "이만희",
    T_URL: null,
    F_URL: "https://web.facebook.com/yc20002",
    Y_URL: "https://www.youtube.com/channel/channel/UCWmrx4i60a40Id2PbsuoOPA/",
    B_URL: "https://blog.naver.com/yc20002",
    MONA_CD: "OSV9142K",
  },
  {
    HG_NM: "이명수",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "6YT83269",
  },
  {
    HG_NM: "이병훈",
    T_URL: null,
    F_URL: "https://web.facebook.com/lbh0318",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "HKJ99607",
  },
  {
    HG_NM: "이상민",
    T_URL: null,
    F_URL: "https://web.facebook.com/esangmin",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ZYH1940A",
  },
  {
    HG_NM: "이상헌",
    T_URL: null,
    F_URL: "https://web.facebook.com/thethethe0613",
    Y_URL: null,
    B_URL: "https://blog.naver.com/leesh_2018",
    MONA_CD: "WVU2479T",
  },
  {
    HG_NM: "이성만",
    T_URL: null,
    F_URL: "https://web.facebook.com/leesungman61",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "8KF7223D",
  },
  {
    HG_NM: "이소영",
    T_URL: null,
    F_URL: "https://web.facebook.com/imsoyoung.kr",
    Y_URL: "https://www.youtube.com/channel/UCWw2YRY-nQFi6MrFVI30jkA",
    B_URL: "https://blog.naver.com/soyoung8lee",
    MONA_CD: "WTR5885Y",
  },
  {
    HG_NM: "이수진",
    T_URL: null,
    F_URL: "https://web.facebook.com/lsj545",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "0R68099X",
  },
  {
    HG_NM: "이수진",
    T_URL: null,
    F_URL: "https://web.facebook.com/leesujin.hope",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "D4L60530",
  },
  {
    HG_NM: "이양수",
    T_URL: null,
    F_URL: "https://web.facebook.com/2yangs6288",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "S9U45255",
  },
  {
    HG_NM: "이용",
    T_URL: null,
    F_URL: "https://web.facebook.com/yong.lee.90410",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "5UN9725L",
  },
  {
    HG_NM: "이용빈",
    T_URL: null,
    F_URL: "https://web.facebook.com/chungsana",
    Y_URL: "https://www.youtube.com/c/이용빈",
    B_URL: "https://blog.naver.com/fmdoc4u",
    MONA_CD: "GKD32201",
  },
  {
    HG_NM: "이용선",
    T_URL: null,
    F_URL: "https://web.facebook.com/yslee9282",
    Y_URL: "https://www.youtube.com/@yslee9282",
    B_URL: null,
    MONA_CD: "9JF4562W",
  },
  {
    HG_NM: "이용우",
    T_URL: "https://twitter.com/minjoolee2020",
    F_URL: "https://web.facebook.com/minjoolee2020",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "G7512472",
  },
  {
    HG_NM: "이용호",
    T_URL: null,
    F_URL: "https://web.facebook.com/victoryyongho",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "DBA1057Z",
  },
  {
    HG_NM: "이원욱",
    T_URL: "https://twitter.com/ewon33",
    F_URL: "https://web.facebook.com/ewon33",
    Y_URL: "https://www.youtube.com/이원욱tv",
    B_URL: "https://blog.naver.com/ewon33",
    MONA_CD: "16D7652C",
  },
  {
    HG_NM: "이원택",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "DAV7257X",
  },
  {
    HG_NM: "이은주",
    T_URL: null,
    F_URL: "https://web.facebook.com/lej515",
    Y_URL: null,
    B_URL: "https://blog.naver.com/lej515.tistory.com",
    MONA_CD: "W1Q6753M",
  },
  {
    HG_NM: "이인선",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "DWK26447",
  },
  {
    HG_NM: "이인영",
    T_URL: "https://twitter.com/lee_inyoung",
    F_URL: "https://web.facebook.com/bigbang1003",
    Y_URL: "https://www.youtube.com/user/leeinyoungTV",
    B_URL: "https://blog.naver.com/liy1964",
    MONA_CD: "3ZR4438W",
  },
  {
    HG_NM: "이장섭",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "7I09543O",
  },
  {
    HG_NM: "이재명",
    T_URL: "https://twitter.com/Jaemyung_Lee",
    F_URL: "https://web.facebook.com/jaemyunglee",
    Y_URL: "https://www.youtube.com/channel/UCNJM6dqu70Qr6VaseiW1Org",
    B_URL: "https://blog.naver.com/jaemyunglee",
    MONA_CD: "IUD9392R",
  },
  {
    HG_NM: "이재정",
    T_URL: "https://twitter.com/lovelylawyerjj",
    F_URL: "https://web.facebook.com/leejjlaw",
    Y_URL: "https://www.youtube.com/channel/channel/UCmGccc0nieB74Q5q5vDJfCw",
    B_URL: "https://blog.naver.com/leejjlaw",
    MONA_CD: "UQ282145",
  },
  {
    HG_NM: "이정문",
    T_URL: null,
    F_URL: "https://web.facebook.com/jongmun.lee.1",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "O0I2045I",
  },
  {
    HG_NM: "이종배",
    T_URL: null,
    F_URL: "https://web.facebook.com/victoryleejb",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "HSW1214Q",
  },
  {
    HG_NM: "이종성",
    T_URL: null,
    F_URL: "https://web.facebook.com/jongseong.i",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "FDC3144T",
  },
  {
    HG_NM: "이주환",
    T_URL: null,
    F_URL: "https://web.facebook.com/Lee.Joo.Hwan",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "3RW63706",
  },
  {
    HG_NM: "이채익",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "WDS6044S",
  },
  {
    HG_NM: "이철규",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "TZP9391O",
  },
  {
    HG_NM: "이탄희",
    T_URL: "https://twitter.com/lee_tanhi",
    F_URL: "https://web.facebook.com/lee.tahney",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "9S151177",
  },
  {
    HG_NM: "이태규",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "QTW6852F",
  },
  {
    HG_NM: "이학영",
    T_URL: "https://twitter.com/hackyoung1",
    F_URL: "https://web.facebook.com/hackyoung1",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "K5F2023J",
  },
  {
    HG_NM: "이해식",
    T_URL: null,
    F_URL: "https://web.facebook.com/leehsik",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CCU1009B",
  },
  {
    HG_NM: "이헌승",
    T_URL: "https://twitter.com/g7member",
    F_URL: "https://web.facebook.com/ilovebusanjin",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "EVH1507C",
  },
  {
    HG_NM: "이형석",
    T_URL: null,
    F_URL: "https://web.facebook.com/hslee2010",
    Y_URL: null,
    B_URL: "https://blog.naver.com/hslee2016",
    MONA_CD: "IOW8224X",
  },
  {
    HG_NM: "인재근",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "UM51067K",
  },
  {
    HG_NM: "임병헌",
    T_URL: null,
    F_URL: "https://web.facebook.com/jungnam.bhlim/",
    Y_URL: null,
    B_URL: "https://blog.naver.com/jungnam-bhlim",
    MONA_CD: "NLR6572J",
  },
  {
    HG_NM: "임오경",
    T_URL: null,
    F_URL: "https://web.facebook.com/okyeong.lim",
    Y_URL: null,
    B_URL: "https://blog.naver.com/oklim777",
    MONA_CD: "4T026790",
  },
  {
    HG_NM: "임이자",
    T_URL: null,
    F_URL: "https://web.facebook.com/llj11",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "EH27538E",
  },
  {
    HG_NM: "임종성",
    T_URL: "https://twitter.com/5321tempia",
    F_URL: "https://web.facebook.com/ijs5321",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "E6U4345C",
  },
  {
    HG_NM: "임호선",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "FH777496",
  },
  {
    HG_NM: "장경태",
    T_URL: "https://twitter.com/jktjj",
    F_URL: "https://web.facebook.com/letskt2016",
    Y_URL: "https://www.youtube.com/c/장경태TV",
    B_URL: "https://blog.naver.com/jktjkt",
    MONA_CD: "RPN2293B",
  },
  {
    HG_NM: "장동혁",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "KFM1081G",
  },
  {
    HG_NM: "장제원",
    T_URL: null,
    F_URL: "https://web.facebook.com/bravojewon",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CZB4125D",
  },
  {
    HG_NM: "장철민",
    T_URL: null,
    F_URL: "https://web.facebook.com/JCM21st",
    Y_URL: "https://www.youtube.com/channel/UCw6T7K4TjXcN7qIQ72-mc-Q",
    B_URL: "https://blog.naver.com/jcm5440",
    MONA_CD: "2NV6751W",
  },
  {
    HG_NM: "장혜영",
    T_URL: "https://twitter.com/janghyeyeong",
    F_URL: "https://web.facebook.com/serious.hyeyeong",
    Y_URL: "https://www.youtube.com/channel/UCGdB-lgTS2sOhJIxgP550qw",
    B_URL: null,
    MONA_CD: "GAV6441G",
  },
  {
    HG_NM: "전봉민",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "DPZ7685X",
  },
  {
    HG_NM: "전용기",
    T_URL: null,
    F_URL: "https://web.facebook.com/jeun.younggi",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "TJW93720",
  },
  {
    HG_NM: "전재수",
    T_URL: "https://twitter.com/gazefor",
    F_URL: "https://web.facebook.com/gazefor",
    Y_URL: "https://www.youtube.com/channel/UCcDu9m1KSSWesVAcwF0tDiw",
    B_URL: "https://blog.naver.com/jsstory7",
    MONA_CD: "9YO73104",
  },
  {
    HG_NM: "전주혜",
    T_URL: null,
    F_URL: "https://web.facebook.com/jjh827",
    Y_URL: null,
    B_URL: "https://blog.naver.com/jhjoy827",
    MONA_CD: "71J2365L",
  },
  {
    HG_NM: "전해철",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "BM63269Y",
  },
  {
    HG_NM: "전혜숙",
    T_URL: null,
    F_URL: "https://web.facebook.com/winner1219",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "N9X9673B",
  },
  {
    HG_NM: "정경희",
    T_URL: null,
    F_URL: "https://web.facebook.com/chungkhrok",
    Y_URL: "https://www.youtube.com/channel/channel/UCslrg1otVlzw-hMBhLSAJ2w",
    B_URL: "https://blog.naver.com/kh7841571",
    MONA_CD: "USR7059P",
  },
  {
    HG_NM: "정동만",
    T_URL: null,
    F_URL: "https://web.facebook.com/dongman.jeong.7",
    Y_URL: null,
    B_URL: "https://blog.naver.com/dongbu1538",
    MONA_CD: "DAY6557K",
  },
  {
    HG_NM: "정성호",
    T_URL: null,
    F_URL: "https://web.facebook.com/jungsungho1",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "V429892C",
  },
  {
    HG_NM: "정우택",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "VHK3402G",
  },
  {
    HG_NM: "정운천",
    T_URL: null,
    F_URL: "https://web.facebook.com/gbs2008",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "NZF1659U",
  },
  {
    HG_NM: "정일영",
    T_URL: null,
    F_URL: "https://web.facebook.com/chung1young",
    Y_URL: null,
    B_URL: "https://blog.naver.com/chung10park",
    MONA_CD: "LT72093S",
  },
  {
    HG_NM: "정점식",
    T_URL: null,
    F_URL: "https://web.facebook.com/jjs0403",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "LJK4960Z",
  },
  {
    HG_NM: "정진석",
    T_URL: null,
    F_URL: "https://web.facebook.com/jinsukchung60",
    Y_URL: "https://www.youtube.com/channel/channel/UC6TTTjZ4Lus1EwGqHWfTgqQ",
    B_URL: "https://blog.naver.com/chungjinsuk",
    MONA_CD: "NQR1206Q",
  },
  {
    HG_NM: "정찬민",
    T_URL: null,
    F_URL: "https://web.facebook.com/jungchanmin1",
    Y_URL: null,
    B_URL: "https://blog.naver.com/jungchanmin",
    MONA_CD: "SBK1544B",
  },
  {
    HG_NM: "정청래",
    T_URL: null,
    F_URL: "https://web.facebook.com/cheongrae1",
    Y_URL: "https://www.youtube.com/user/ssabibi",
    B_URL: "https://blog.naver.com/mapopower",
    MONA_CD: "2385336L",
  },
  {
    HG_NM: "정춘숙",
    T_URL: null,
    F_URL: "https://web.facebook.com/jchounsook",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "MD083627",
  },
  {
    HG_NM: "정태호",
    T_URL: "https://twitter.com/Jung_Taeho?form=MY01SV&amp;OCID=MY01SV",
    F_URL: "https://web.facebook.com/JungTaeHo ",
    Y_URL: "https://www.youtube.com/channel/channel/UCGrIqmBh85ToDm8qthbDKlA",
    B_URL: "https://blog.naver.com/2000jth",
    MONA_CD: "UHB5553T",
  },
  {
    HG_NM: "정필모",
    T_URL: null,
    F_URL: "https://web.facebook.com/pmjung537",
    Y_URL: null,
    B_URL: "https://blog.naver.com/pmjung537",
    MONA_CD: "3425169D",
  },
  {
    HG_NM: "정희용",
    T_URL: null,
    F_URL: "https://web.facebook.com/heeyong4u",
    Y_URL: "https://www.youtube.com/channel/channel/UCTp7oLtzv3U7w0deSXAUlTA",
    B_URL: "https://blog.naver.com/heeyong4you",
    MONA_CD: "PFG2137X",
  },
  {
    HG_NM: "조경태",
    T_URL: "https://twitter.com/Choforce",
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "5KV82250",
  },
  {
    HG_NM: "조명희",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "S741317G",
  },
  {
    HG_NM: "조수진",
    T_URL: null,
    F_URL: "https://web.facebook.com/chosujin2020",
    Y_URL: "https://www.youtube.com/channel/UCOSl0SuO3e-1PZLc8npWLcg",
    B_URL: "https://blog.naver.com/assembly2020",
    MONA_CD: "YLS4431M",
  },
  {
    HG_NM: "조승래",
    T_URL: null,
    F_URL: "https://web.facebook.com/gasiri7",
    Y_URL: "https://www.youtube.com/gasiri7",
    B_URL: null,
    MONA_CD: "FYI20317",
  },
  {
    HG_NM: "조오섭",
    T_URL: null,
    F_URL: "https://web.facebook.com/hanaking7979",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "25I8709Q",
  },
  {
    HG_NM: "조은희",
    T_URL: null,
    F_URL: "https://web.facebook.com/gracecho1127",
    Y_URL: "https://www.youtube.com/channel/channel/UCeDCV1lNqEE9aKmn43RNxeA",
    B_URL: "https://blog.naver.com/gracecho1",
    MONA_CD: "MQU41854",
  },
  {
    HG_NM: "조응천",
    T_URL: null,
    F_URL: "https://web.facebook.com/chopros",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "CDL93608",
  },
  {
    HG_NM: "조정식",
    T_URL: "https://twitter.com/chojs21",
    F_URL: "https://web.facebook.com/chojs21",
    Y_URL: "https://www.youtube.com/c/조정식TV",
    B_URL: null,
    MONA_CD: "IN328264",
  },
  {
    HG_NM: "조정훈",
    T_URL: "https://twitter.com/chojunghun544",
    F_URL: "https://web.facebook.com/544chojunghun",
    Y_URL: "https://www.youtube.com/@chojunghun544",
    B_URL: "https://blog.naver.com/chojunghun544",
    MONA_CD: "WJL30106",
  },
  {
    HG_NM: "조해진",
    T_URL: null,
    F_URL: "https://web.facebook.com/chrisjo204?form=MY01SV&amp;OCID=MY01SV",
    Y_URL: "https://www.youtube.com/channel/UCq7UY3Hgy4DikDli1WpqeUQ/featured",
    B_URL: "https://blog.naver.com/chrisjo631",
    MONA_CD: "Z6R3959C",
  },
  {
    HG_NM: "주철현",
    T_URL: null,
    F_URL: "https://web.facebook.com/yeosumayor",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "T465023H",
  },
  {
    HG_NM: "주호영",
    T_URL: "https://twitter.com/@sangtoil",
    F_URL: "https://web.facebook.com/@sangtoil",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "8SV6917G",
  },
  {
    HG_NM: "지성호",
    T_URL: "https://twitter.com/jiseong0403",
    F_URL: "https://web.facebook.com/seongho.ji.18",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "Y7K5946R",
  },
  {
    HG_NM: "진선미",
    T_URL: "https://twitter.com/sunmee_jin",
    F_URL: "https://web.facebook.com/smjingogo",
    Y_URL: "https://www.youtube.com/channel/UCJjg88xb_nV020aichTln3A",
    B_URL: "https://blog.naver.com/smjingogo",
    MONA_CD: "68P7228G",
  },
  {
    HG_NM: "진성준",
    T_URL: "https://twitter.com/jinsungjoon",
    F_URL: "https://web.facebook.com/hotjjoon",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "3C23171A",
  },
  {
    HG_NM: "천준호",
    T_URL: null,
    F_URL: "https://web.facebook.com/juno3355",
    Y_URL: "https://www.youtube.com/channel/channel/UCQ8jaYT5yXKxavGPcKsftgw",
    B_URL: "https://blog.naver.com/junocheon",
    MONA_CD: "A494529E",
  },
  {
    HG_NM: "최강욱",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "ICH23251",
  },
  {
    HG_NM: "최기상",
    T_URL: null,
    F_URL: "https://web.facebook.com/gisang2020",
    Y_URL: "https://www.youtube.com/@ChoiKiSang",
    B_URL: "https://blog.naver.com/gisang2020",
    MONA_CD: "I5I2468R",
  },
  {
    HG_NM: "최승재",
    T_URL: null,
    F_URL: "https://web.facebook.com/choisj2284",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "M7T9712V",
  },
  {
    HG_NM: "최연숙",
    T_URL: null,
    F_URL: "https://web.facebook.com/cysook915",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "8VJ8533R",
  },
  {
    HG_NM: "최영희",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "YTA7297R",
  },
  {
    HG_NM: "최인호",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "LPB30152",
  },
  {
    HG_NM: "최재형",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/choejh0902",
    MONA_CD: "6RM29022",
  },
  {
    HG_NM: "최종윤",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "Z7Y7827F",
  },
  {
    HG_NM: "최춘식",
    T_URL: null,
    F_URL: "https://web.facebook.com/cschoi2018",
    Y_URL: null,
    B_URL: "https://blog.naver.com/m.cschoi415",
    MONA_CD: "3DK8989T",
  },
  {
    HG_NM: "최형두",
    T_URL: null,
    F_URL: "https://web.facebook.com/https://www.facebook.com/hd.choi",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "A0P4646G",
  },
  {
    HG_NM: "최혜영",
    T_URL: null,
    F_URL: "https://web.facebook.com/profile.php?id=100047325760674",
    Y_URL:
      "https://www.youtube.com/channel/channel/UC0GYAU9BLS7Hxu6vk9eUYWQ?view_as=subscriber",
    B_URL: "https://blog.naver.com/chy-647",
    MONA_CD: "QD25323M",
  },
  {
    HG_NM: "추경호",
    T_URL: null,
    F_URL: "https://web.facebook.com/ChooKyungho",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "G152611B",
  },
  {
    HG_NM: "태영호",
    T_URL: null,
    F_URL: "https://web.facebook.com/https://www.facebook.com/TYHGangNam",
    Y_URL: "https://www.youtube.com/https://www.youtube.com/태영호tv",
    B_URL: null,
    MONA_CD: "XJC13432",
  },
  {
    HG_NM: "하영제",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "FGI27280",
  },
  {
    HG_NM: "하태경",
    T_URL: "https://twitter.com/taekyungh",
    F_URL: "https://web.facebook.com/radiohahapage",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "I0S53762",
  },
  {
    HG_NM: "한기호",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/nombo1",
    MONA_CD: "JQA21112",
  },
  {
    HG_NM: "한무경",
    T_URL: null,
    F_URL: "https://web.facebook.com/profile.php?id=100051853488886",
    Y_URL: "https://www.youtube.com/channel/UCtlwF4bGq1m06E9GpT7xghQ",
    B_URL: "https://blog.naver.com/hanmk2021",
    MONA_CD: "UB114374",
  },
  {
    HG_NM: "한병도",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "H5476989",
  },
  {
    HG_NM: "한정애",
    T_URL: "https://twitter.com/dudehowru",
    F_URL: "https://web.facebook.com/jeongae.han",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "XPP2564T",
  },
  {
    HG_NM: "한준호",
    T_URL: "https://twitter.com/juno_news",
    F_URL: "https://web.facebook.com/hanjuno.news",
    Y_URL: "https://www.youtube.com/c/한준호의목소리",
    B_URL: "https://blog.naver.com/juno_news",
    MONA_CD: "BCQ55105",
  },
  {
    HG_NM: "허영",
    T_URL: "https://twitter.com/doingbeing",
    F_URL: "https://web.facebook.com/doingbeing",
    Y_URL: "https://www.youtube.com/c/huhyoung",
    B_URL: "https://blog.naver.com/ramman",
    MONA_CD: "FU53642G",
  },
  {
    HG_NM: "허은아",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "66W6739S",
  },
  {
    HG_NM: "허종식",
    T_URL: null,
    F_URL: "https://web.facebook.com/heojongsik",
    Y_URL: null,
    B_URL: "https://blog.naver.com/jongsyy",
    MONA_CD: "VCP96419",
  },
  {
    HG_NM: "홍기원",
    T_URL: null,
    F_URL: "https://web.facebook.com/hongkw.win",
    Y_URL: "https://www.youtube.com/c/평택홍기원",
    B_URL: "https://blog.naver.com/flyhong21",
    MONA_CD: "5MD4184K",
  },
  {
    HG_NM: "홍문표",
    T_URL: null,
    F_URL: "https://web.facebook.com/munpyo.hong",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "GD131760",
  },
  {
    HG_NM: "홍석준",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "EMC8812P",
  },
  {
    HG_NM: "홍성국",
    T_URL: null,
    F_URL: "https://web.facebook.com/sejonghsk",
    Y_URL: null,
    B_URL: "https://blog.naver.com/hong2240",
    MONA_CD: "2N793392",
  },
  {
    HG_NM: "홍영표",
    T_URL: "https://twitter.com/YoungpyoHong",
    F_URL: "https://web.facebook.com/youngvote1004",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "KR14136C",
  },
  {
    HG_NM: "홍익표",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "FRN1867O",
  },
  {
    HG_NM: "홍정민",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: "https://blog.naver.com/waytohong",
    MONA_CD: "XA42275R",
  },
  {
    HG_NM: "황보승희",
    T_URL: null,
    F_URL: "https://web.facebook.com/0415hbsh",
    Y_URL: "https://www.youtube.com/c/황보승희TV",
    B_URL: "https://blog.naver.com/ven76",
    MONA_CD: "J9S37905",
  },
  {
    HG_NM: "황운하",
    T_URL: null,
    F_URL: "https://web.facebook.com/unha.hwang",
    Y_URL: null,
    B_URL: null,
    MONA_CD: "0YT3774N",
  },
  {
    HG_NM: "황희",
    T_URL: null,
    F_URL: null,
    Y_URL: null,
    B_URL: null,
    MONA_CD: "0VU8517U",
  },
];
